.\" lfstoolkit
.TH "lfstoolkit" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
lfstoolkit \- manual page for lfstoolkit 0.0.0
.SH "SYNOPSIS"
.B lfstoolkit
.SH "DESCRIPTION"
A CLI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
lfstoolkit
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
