#!/bin/bash -e

#©keithhedger Fri 6 Nov 11:13:35 GMT 2015 kdhedger68713@gmail.com

PREFIX="/usr"
STAGING=

for arg in LFSToolKit LFSSetWallpaper LFSDesktop LFSWManager LFSPanel LFSApplications
	do
		tar -xvf ${arg}-*.tar.gz
		pushd ${arg}
			./configure --prefix=${PREFIX};make||./autogen.sh --prefix=${PREFIX};make||(echo "Configure Error...";exit 1)
			if [ $arg = "LFSToolKit" ];then
				make purge DESTDIR=${STAGING}
			fi
			make install DESTDIR=${STAGING}
		
			if [ $arg = "LFSToolKit" ];then
				ldconfig
			fi

		popd
	done