#!/bin/bash -e

#©keithhedger Fri 6 Nov 11:13:35 GMT 2015 kdhedger68713@gmail.com

PREFIX="/usr"
STAGING=
LDCONFIG="/sbin/ldconfig"

for arg in LFSToolKit LFSSetWallpaper LFSDesktop LFSWManager LFSPanel LFSApplications
	do
		tar -xvf ${arg}-*.tar.gz
		pushd ${arg}
			./configure --prefix=${PREFIX}||./autogen.sh --prefix=${PREFIX}||(echo "Configure Error...";exit 1)
			make
			if [ $arg = "LFSToolKit" ];then
				make purge DESTDIR=${STAGING}||true
			fi
			make install DESTDIR=${STAGING}
		
			if [ $arg = "LFSToolKit" ];then
				$LDCONFIG
			fi

		popd
	done