#!/bin/bash -e

#©keithhedger Mon 18 May 11:32:59 BST 2015 kdhedger68713@gmail.com

wallpaperversion=$(sed -n '/#define VERSION/p' LFSSetWallpaper/config.h|awk '{print $3}'|sed 's/"//g')
desktopversion=$(sed -n '/#define VERSION/p' LFSDesktop/config.h|awk '{print $3}'|sed 's/"//g')
wmversion=$(sed -n '/#define VERSION/p' LFSWManager/config.h|awk '{print $3}'|sed 's/"//g')
tkversion=$(sed -n '/#define VERSION/p' LFSToolKit/config.h|awk '{print $3}'|sed 's/"//g')
lfsappsversion=$(sed -n '/#define VERSION/p' LFSApplications/config.h|awk '{print $3}'|sed 's/"//g')

rm -r /tmp/tmp||true
mkdir /tmp/tmp
pushd /tmp/tmp
	svn co file:///media/LinuxData/Development/SVN/LFSDesktopProject/LFSDesktop
	rm -r LFSDesktop/.svn
	tar -cvzf LFSDesktop-$desktopversion.tar.gz LFSDesktop

	svn co file:///media/LinuxData/Development/SVN/LFSDesktopProject/LFSSetWallpaper
	rm -r SetWallpaper/.svn
	tar -cvzf LFSSetWallpaper-$wallpaperversion.tar.gz LFSSetWallpaper

	svn co file:///media/LinuxData/Development/SVN/LFSDesktopProject/LFSWManager
	rm -r LFSWManager/.svn
	debugfile=$(readlink LFSWManager/LFSWManager/src/debug.h)
	rm LFSWManager/LFSWManager/src/debug.h
	cp -fv "${debugfile}" LFSWManager/LFSWManager/src
	tar -cvzf LFSWManager-$wmversion.tar.gz LFSWManager

	svn co file:///media/LinuxData/Development/SVN/LFSDesktopProject/LFSToolKit
	rm -r LFSToolKit/.svn
	tar -cvzf LFSToolKit-$tkversion.tar.gz LFSToolKit

	svn co file:///media/LinuxData/Development/SVN/LFSDesktopProject/LFSApplications
	rm -r LFSApplications/.svn
	tar -cvzf LFSApplications-$tkversion.tar.gz LFSApplications
popd

