#!/bin/bash -e

#©keithhedger Fri 6 Nov 11:13:35 GMT 2015 kdhedger68713@gmail.com

PREFIX="/usr"
STAGING=

for arg in LFSToolKit LFSSetWallpaper LFSDesktop LFSWManager LFSPanel LFSApplications
	do
		pushd ${arg}
			if [ $arg = "LFSToolKit" ];then
				make purge||true
			else
				make uninstall||true
			fi
		popd
	done