.TH "LFSSETWALLPAPER" "1" "October 2015" "setlfswalpaper 0.0.5" "User Commands"
.SH "NAME"
\fBlfssetwallpaper\fR - manual page for lfssetwallpaper 0.0.5
.br

.SH "SYNOPSIS"
\fBlfssetwallpaper \fR[\fIOPTION\fR]
.br

.SH "DESCRIPTION"
Set the desktop wallpaper for LFSDesktop
.br

\fB-w\fR,--wallpaper \fI/path/to/wallpaper\fR ARG
.br

\fB-c\fR,--colour
.br
       Background colour N (decimal or hex)
.br

\fB-a\fR,--mainmode
.br
       Main Mode (Stretch=0,Tile=1,Centre=2,Scaled=3,Zoomed=4) N
.br

\fB-o\fR,--monitormode
.br
       Mode for individual monitors (as above) N
.br

\fB-m\fR,--monitor
.br
       Monitor number N
.br

\fB-y\fR,--multimode
.br
       Multi monitor image mode 0=Single image,1=Multi image N
.br

\fB-v\fR,--version
.br
       output version information and exit
.br

\fB-h\fR,-?,--help
.br
       print this help
.br

.SH "REPORTING BUGS"
Report bugs to kdhedger68713@gmail.com
.br

