.TH "LFSDESKTOP" "1" "June 2015" "lfsdesktop 0.0.9" "User Commands"
.SH "NAME"
lfsdesktop - manual page for lfsdesktop 0.0.9
.br

.SH "SYNOPSIS"
\fBlfsdesktop \fR[\fIOPTION\fR] ...
.br

.SH "DESCRIPTION"
LFSDesktop - 0.0.9
.br

\fB-c\fR,--clean
.br
       Clean disk info/desktop cache data
.br

\fB-t\fR,--tidy
.br
       Tidy disk info/desktop cache data preserving existing
.br

\fB-a\fR,--theme
.br
       Set theme
.br

\fB-x\fR,--term-command
.br
       Set terminal command ( default xterm \fB-e \fR)
.br

\fB-s\fR,--show-extension
.br
       Set terminal command ( default xterm \fB-e \fR)
.br

\fB-f\fR,--font
.br
       Font face ( Sans;0;0;10 - Fontname;Weight(0/1);Slant(0/1/2);Fontsize )
.br

\fB-4\fR,--fore-colour
.br
       Fore colour for label in RGBA hex notation ( default 0xffffffff )
.br

\fB-b\fR,--back-colour
.br
       Back colour for label in RGBA hex notation ( default 0x0 )
.br

\fB-i\fR,--ignore
.br
       List of ';' seperated disk labels to NOT show on desktop
.br

\fB-d\fR,--debug
.br
       Debug
.br

\fB-v\fR,--version
.br
       output version information and exit
.br

\fB-h\fR,-?,--help
.br
       print this help
.br

.SH "FILES"
A Sample prefs file is below this should be placed in ~/.config/LFS/lfsdesktop.rc, configure to suit yourself.
.br

icontheme nouveGnomeSteel
.br
iconsize 32
.br
gridborder 32
.br
refreshrate 2
.br
fontface Sans;1;0;10
.br
labelforeground 0xffffffff
.br
labelbackground 0x10101060
.br
noshow PQSERVICE;DATA;SYSTEM_RESERVED;
.br
.SH "REPORTING BUGS"
Report bugs to kdhedger68713@gmail.com
.br

