.TH "LFSDESKTOP" "1" "June 2015" "lfsdesktop 0.0.8" "User Commands"
.SH "NAME"
lfsdesktop - manual page for lfsdesktop 0.0.8
.br
.SH "SYNOPSIS"
\fBlfsdesktop \fR[\fIOPTION\fR] ...
.br
.SH "DESCRIPTION"
LFSDesktop - 0.0.8
.br

\fB-c\fR,--clean
.br
       Clean disk info/desktop cache data
.br

\fB-t\fR,--tidy
.br
       Tidy disk info/desktop cache data preserving existing
.br

\fB-a\fR,--theme
.br
       Set theme
.br

\fB-x\fR,--term-command
.br
       Set terminal command ( default xterm \fB-e \fR)
.br

\fB-s\fR,--show-extension
.br
       Set terminal command ( default xterm \fB-e \fR)
.br

\fB-d\fR,--debug
.br
       Debug
.br

\fB-v\fR,--version
.br
       output version information and exit
.br

\fB-h\fR,-?,--help
.br
       print this help
.br

.SH "REPORTING BUGS"
Report bugs to kdhedger68713@gmail.com
.br

