.\" lfsdesktop
.TH "lfsdesktop" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
lfsdesktop \- manual page for lfsdesktop 0.0.0
.SH "SYNOPSIS"
.B lfsdesktop
.SH "DESCRIPTION"
A CLI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
lfsdesktop
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
